### ISSUE TITLE
context cancellation allows duplicate .Dos to execute concurrently

### ISSUE THREAD

**Issue by ldeffenb** [janos/singleflight#4]
The .Do method is supposed to ensure that multiple calls for a single key are queued to a single execution with the result being returned to all invokers.   This works as long as none of the invokers have a context cancellation while the .Do function is executing.

If any invoker's context is cancelled, its wait() will complete and REMOVE the key from the calls map at line 80. 
https://github.com/janos/singleflight/blob/99e6620ca5bea458c23bfe738c77a87496865e09/singleflight.go#L80

Any new invokers of .Do with the same key will not find the still-executing previous instance, but will allow an entirely new execution of the function to begin.

I believe the removal of key from the dictionary should ONLY happen when the counter is zero indicating that there are no other waiters on this particular key.
https://github.com/janos/singleflight/blob/99e6620ca5bea458c23bfe738c77a87496865e09/singleflight.go#L77

Otherwise, the singleflight assurance of only a single concurrently executing function for any given key is violated instant any context is cancelled.

I discovered this by watching the singleflight usage in the bee client pullsync code and have observed multiple executions of the function for a given key whenever a cancellation occurs.   I then created a local copy of the singleflight code with the fix proposed above and the multiple concurrent exeuctions for a key no longer occur, but all remaining non-cancelled invokers of .Do are completed with the shared result when the actual invocation completes.

And after the current execution completes, a new instance of the .Do function IS properly invoked the next time someone uses the same key.

**Comment by janos** [comment]
Hey, @ldeffenb. Thank you so much for nice details and the proposed solution. You are spot on. I have made a PR #5 to fix the issue. Could you check the changes there?

**Comment by ldeffenb** [comment]
I'll try to get this built into my -dirty testnet version sometime over the weekend and watch my singleflight logs.   I put a singleflight around the Cursors retrieval as I have a node that has LOTS of chunks pinned and in 1.16 the Cursors calls were taking 10-20-30 seconds each at 100% cpu and 50-100 of them executing concurrently.

I haven't looked at the Cursors retrieval performance on 1.17 yet though, so I might not need this particular hack.  I'm hoping to start with stock 1.17 and slow bring in my earlier hacks as needed, and maybe actually make PRs out of them now that I've cleaned up my fork.
